"""initial schema

Revision ID: bb99816fdc31
Revises: 
Create Date: 2026-06-01 12:08:38.193873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'bb99816fdc31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_for', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('found', 'missing', 'wrong_version', name='dependencystatus'), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('install_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_dependency_name')
    )
    op.create_table('device',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sa.Enum('mac', 'linux', 'iphone', 'ipad', 'usb_drive', 'hard_drive', name='devicetype'), nullable=False),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('registered', 'cataloging', 'cataloged', 'analyzing', 'analyzed', 'migrating', 'migrated', 'verifying', 'verified', 'wiping', 'wiped', 'recycled', name='devicestage'), nullable=False),
    sa.Column('staging_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplicategroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('canonical_entry_id', sa.Integer(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_entry_id'], ['file_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relative_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mtime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'keep', 'discard', 'migrated', 'verified', name='filestatus'), nullable=False),
    sa.Column('duplicate_group_id', sa.Integer(), nullable=True),
    sa.Column('restic_snapshot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['duplicate_group_id'], ['duplicategroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fileentry_device_status', 'file_entry', ['device_id', 'status'], unique=False)
    op.create_index('ix_fileentry_sha256', 'file_entry', ['sha256'], unique=False)
    op.create_table('storagetarget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('backend', sa.Enum('local', 'sftp', 's3', name='storagebackend'), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('restic_password_env', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('catalog', 'ios_extract', 'migrate', 'verify', 'wipe', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('log_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('storage_target_id', sa.Integer(), nullable=False),
    sa.Column('restic_snapshot_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('added_bytes', sa.Integer(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['storage_target_id'], ['storagetarget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    op.drop_table('job')
    op.drop_table('storagetarget')
    op.drop_index('ix_fileentry_sha256', table_name='file_entry')
    op.drop_index('ix_fileentry_device_status', table_name='file_entry')
    op.drop_table('file_entry')
    op.drop_table('duplicategroup')
    op.drop_table('device')
    op.drop_table('dependency')
    # ### end Alembic commands ###
